^XA~TA000~JSN^LT0^MNW^MTD^PON^PMN^LH0,0^JMA^PR2,2~SD15^JUS^LRN^CI0^XZ
^XA
^MMT
^PW831
^LL0959
^LS0
^FT762, 250^A0R, 85, 84^FH\^FDSDA^FS
^FT730, 250^A0R, 23, 24^FH\^FDEXPRESS COURIER^FS
^FT793, 610^A0R, 23, 24^FH\^FDNumero Unico^FS
^FT757, 610^A0R, 23, 24^FH\^FD199 - 113366^FS
^FT725, 610^A0R, 23, 24^FH\^FDwww.sda.it^FS
^FT793, 800^A0R, 23, 24^FH\^FDdata partenza^FS
^FT762, 800^A0R, 23, 24^FH\^FD@data_spedizione^FS
^FT695, 250^A0R, 29, 33^FH\^FD@descrizione_servizio^FS
^FT662, 250^A0R, 23, 24^FH\^FDRif Sped.:@tipo_documento^FS
^FO652, 250^GB0, 470, 1^FS
^FT632, 250^A0R, 17, 16^FH\^FDMittente^FS
^FT607, 250^A0R, 28, 28^FH\^FD@dit_descrizione1^FS
^FT581, 250^A0R, 28, 28^FH\^FD@dit_descrizione2^FS
^FT554, 250^A0R, 28, 28^FH\^FD@dit_via^FS
^FT527, 250^A0R, 28, 28^FH\^FD@dit_cap^FS
^FT503, 250^A0R, 28, 28^FH\^FDContatto: @dit_contatto^FS
^FO496, 250^GB0, 470, 1^FS
^FT480, 250^A0R, 17, 16^FH\^FDDestinatario^FS
^FT457, 250^A0R, 28, 28^FH\^FD@cli_descrizione1^FS
^FT428, 250^A0R, 28, 28^FH\^FD@cli_descrizione2^FS
^FT402, 250^A0R, 28, 28^FH\^FD@cli_via^FS
^FT376, 250^A0R, 28, 28^FH\^FD@cli_cap^FS
^FT350, 250^A0R, 28, 28^FH\^FDContatto: @cli_contatto^FS
^FT324, 250^A0R, 28, 28^FH\^FDtelefono: @cli_telefono^FS
^FT300, 250^A0R, 17, 16^FH\^FDNote: @testo_note^FS
^FO281, 250^GB0, 470, 1^FS
^FT234, 250^A0R, 17, 16^FH\^FDlettera di vettura^FS
^FT234, 550^A0R, 17, 16^FH\^FDHxLxP(cm)^FS
^FT234, 850^A0R, 17, 16^FH\^FDcolli^FS
^FT234, 700^A0R, 17, 16^FH\^FDpeso(kg)^FS
^FT204, 250^A0R, 28, 28^FH\^FD@progressivo_ldv_multicollo^FS
^FT204, 550^A0R, 23, 24^FH\^FD@dimensioni^FS
^FT204, 850^A0R, 23, 24^FH\^FD@nr_collo^FS
^FT204, 700^A0R, 23, 24^FH\^FD@peso_documento^FS
^FO171, 250^GB0, 470, 1^FS
^FT152, 250^A0R, 17, 16^FH\^FD@spedizione_in_contrassegno^FS
^FT131, 250^A0R, 23, 24^FH\^FD@testo_importo^FS
^FT111, 250^A0R, 23, 24^FH\^FD@testo_importo_lettere^FS
^FT131, 650^A0R, 23, 24^FH\^FD@importo^FS
^FT131,250^A0R, 23, 24^FH\^FD@testo_vedi_ldv_madre^FS
^FT111, 650^A0R, 23, 24^FH\^FD@importo_lettere^FS
^FT90, 250^A0R, 17, 16^FH\^FD@pagamento^FS
^FT90, 363^A0R, 23, 24^FH\^FD@descrizione_pagamento^FS
^FT70, 250^A0R, 17, 16^FH\^FDla presente \8A una lettera di vettura non negoziabile regolata esclusivamente^FS
^FT55, 250^A0R, 17, 16^FH\^FDdalle condizioni generali di trasporto riportate sul modulo vendita che il^FS
^FT40, 250^A0R, 17, 16^FH\^FDmittente dichiara di avere esaminato ed accettato^FS
