CREATE TRIGGER T_ARTMR_BI_0
  BEFORE INSERT
  ON `artmr`
  FOR EACH ROW
BEGIN 


IF NEW.PROGRESSIVO = 0 THEN
  CALL P_CAMPO_VUOTO('artmr', 'progressivo');
END IF;

IF NEW.RIGA = 0 THEN
  CALL P_CAMPO_VUOTO('artmr', 'riga');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
