CREATE TRIGGER T_ARF_BI_0
  BEFORE INSERT
  ON `arf`
  FOR EACH ROW
BEGIN 


IF NEW.ART_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('arf', 'art_codice');
END IF;

IF NEW.FRN_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('arf', 'art_codice');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
