CREATE TRIGGER T_ARA_BI_0
  BEFORE INSERT
  ON `ara`
  FOR EACH ROW
BEGIN 


IF NEW.ART_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('ara', 'art_codice');
END IF;
IF NEW.RIFERIMENTO = '' THEN
  CALL P_CAMPO_VUOTO('ara', 'riferimento');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
