CREATE TRIGGER T_ASS_CARICHE_BI_0
  BEFORE INSERT
  ON ASS_CARICHE
  FOR EACH ROW
BEGIN

IF NEW.PROGRESSIVO = 0 THEN
  CALL P_CAMPO_VUOTO('ass_cariche', 'progressivo');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
