CREATE TRIGGER T_ASS_ATTIVITA_BI_0
  BEFORE INSERT
  ON ASS_ATTIVITA
  FOR EACH ROW
BEGIN

IF NEW.PROGRESSIVO = 0 THEN
  CALL P_CAMPO_VUOTO('ass_attivita', 'progressivo');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
