CREATE TRIGGER T_ASS_SOCI_BI_0
  BEFORE INSERT
  ON ASS_SOCI
  FOR EACH ROW
BEGIN

IF NEW.PROGRESSIVO = 0 THEN
  CALL P_CAMPO_VUOTO('ass_soci', 'progressivo');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
