CREATE TRIGGER T_ASS_QUOTA_TESSERE_BI_0
  BEFORE INSERT
  ON ASS_QUOTA_TESSERE
  FOR EACH ROW
BEGIN

IF NEW.PROGRESSIVO = 0 THEN
  CALL P_CAMPO_VUOTO('ass_quota_tessere', 'progressivo');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
