CREATE TRIGGER T_ASS_SOCI_ATTIVITA_BI_0
  BEFORE INSERT
  ON ASS_SOCI_ATTIVITA
  FOR EACH ROW
BEGIN

IF NEW.ASS_SOCI_PROGRESSIVO = 0 THEN
  CALL P_CAMPO_VUOTO('ass_soci_attivita', 'ass_soci_progressivo');
END IF;

IF NEW.ASS_ATTIVITA_PROGRESSIVO = 0 THEN
  CALL P_CAMPO_VUOTO('ass_soci_attivita', 'ass_attivita_progressivo');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
