CREATE TRIGGER T_ATD_BI_0
  BEFORE INSERT
  ON `atd`
  FOR EACH ROW
BEGIN 


IF NEW.PROGRESSIVO = 0 THEN
  CALL P_CAMPO_VUOTO('atd', 'progressivo');
END IF;

IF NEW.DESCRIZIONE = '' THEN
  CALL P_CAMPO_VUOTO('atd', 'descrizione');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
