CREATE TRIGGER T_ATR_BI_0
  BEFORE INSERT
  ON `atr`
  FOR EACH ROW
BEGIN 


IF NEW.PROGRESSIVO = 0 THEN
  CALL P_CAMPO_VUOTO('atr', 'progressivo');
END IF;

IF NEW.RIGA = 0 THEN
  CALL P_CAMPO_VUOTO('atr', 'riga');
END IF;

IF NEW.NUMERO_IMPIANTI < 1 THEN
  SET NEW.NUMERO_IMPIANTI = 1;
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
