CREATE TRIGGER T_BVCMRR_BI_0
  BEFORE INSERT
  ON `bvcmrr`
  FOR EACH ROW
BEGIN 


IF NEW.PROGRESSIVO = 0 THEN
  CALL P_CAMPO_VUOTO('bvcmrr', 'progressivo');
END IF;

IF NEW.RIGA = 0 THEN
  CALL P_CAMPO_VUOTO('bvcmrr', 'riga');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
