CREATE TRIGGER T_BVR_BU_0
  BEFORE UPDATE
  ON `bvr`
  FOR EACH ROW
BEGIN 


IF NEW.ART_CODICE <> '' AND NEW.TIPO_MOVIMENTO = 'sconto merce' AND
(SELECT TIV_CODICE_SCONTO_MERCE FROM ARC.DIT03 WHERE CODICE = @DIT_CODICE) <> '' THEN
  SET NEW.TIV_CODICE = (SELECT TIV_CODICE_SCONTO_MERCE FROM ARC.DIT03 WHERE CODICE = @DIT_CODICE);
END IF;

IF NEW.ART_CODICE <> '' AND NEW.TUM_CODICE = '' THEN
  SET NEW.TUM_CODICE = (SELECT CASE WHEN TUM_CODICE_VENDITE = '' THEN TUM_CODICE ELSE TUM_CODICE_VENDITE END FROM ART WHERE CODICE = NEW.ART_CODICE);
END IF;

IF NEW.ART_CODICE <> '' THEN
  IF NEW.TUM_QUANTITA_BASE = 0 THEN
	SET NEW.TUM_QUANTITA_BASE = NEW.QUANTITA;
  END IF;
  IF NEW.TUM_QUANTITA_EVASA_BASE = 0 THEN
	SET NEW.TUM_QUANTITA_EVASA_BASE = NEW.QUANTITA_EVASA;
  END IF;
  IF NEW.TUM_QUANTITA_APPRONTATA_BASE = 0 THEN
	SET NEW.TUM_QUANTITA_APPRONTATA_BASE = NEW.QUANTITA_APPRONTATA;
  END IF;
END IF;

END
