CREATE TRIGGER T_CAR_AI
  AFTER INSERT
  ON `car`
  FOR EACH ROW
BEGIN 

IF NEW.DATA_PUNTI IS NOT NULL THEN

CALL P_CAR_CAT_PTI
(NEW.CLI_CODICE_PUNTI, NEW.DATA_PUNTI, NEW.IMPORTO_PUNTI_UTILIZZATO);

END IF;

END
