CREATE TRIGGER T_CAR_AU
  AFTER UPDATE
  ON `car`
  FOR EACH ROW
BEGIN 

if OLD.IMPORTO_PUNTI_UTILIZZATO <> new.IMPORTO_PUNTI_UTILIZZATO then

CALL P_CAR_CAT_PTI
(OLD.CLI_CODICE_PUNTI, OLD.DATA_PUNTI, OLD.IMPORTO_PUNTI_UTILIZZATO * -1);

CALL P_CAR_CAT_PTI
(NEW.CLI_CODICE_PUNTI, NEW.DATA_PUNTI, NEW.IMPORTO_PUNTI_UTILIZZATO);

end if;

END
