CREATE TRIGGER T_CAT_AD
  AFTER DELETE
  ON `cat`
  FOR EACH ROW
BEGIN 
/*
CALL P_CAT_PVT('D', OLD.PVT_PROGRESSIVO, OLD.PVR_RIGA);
*/

IF OLD.DATA_PUNTI IS NOT NULL THEN
  CALL P_CAR_CAT_PTI(OLD.CLI_CODICE, OLD.DATA_PUNTI, OLD.IMPORTO_PUNTI_UTILIZZATO * -1);
END IF;

END
