CREATE TRIGGER T_CAR_AD
  AFTER DELETE
  ON `car`
  FOR EACH ROW
BEGIN 

IF OLD.DATA_PUNTI IS NOT NULL THEN

CALL P_CAR_CAT_PTI
(OLD.CLI_CODICE_PUNTI, OLD.DATA_PUNTI, OLD.IMPORTO_PUNTI_UTILIZZATO * -1);

END IF;

END
