CREATE TRIGGER T_CAC_BI_0
  BEFORE INSERT
  ON `cac`
  FOR EACH ROW
BEGIN 


IF NEW.ART_CODICE = '' OR NEW.CEN_CODICE = '' THEN
  SET NEW.ART_CODICE = null;
END IF;

IF NEW.ART_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('cac', 'art_codice');
END IF;

IF NEW.CEN_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('cac', 'cen_codice');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
