CREATE TRIGGER T_CCF_BI_0
  BEFORE INSERT
  ON `ccf`
  FOR EACH ROW
BEGIN 


IF NEW.PROGRESSIVO = 0 THEN
  CALL P_CAMPO_VUOTO('ccf', 'progressivo');
END IF;

IF NEW.CFG_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('ccf', 'cfg_codice');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
