CREATE TRIGGER T_CEM_BI_0
  BEFORE INSERT
  ON `cem`
  FOR EACH ROW
BEGIN 


IF NEW.DATA_COMPETENZA IS NULL THEN
  SET NEW.DATA_COMPETENZA = NEW.DATA_REGISTRAZIONE;  
END IF;

IF NEW.PROGRESSIVO = 0 THEN
  CALL P_CAMPO_VUOTO('cem', 'progressivo');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
