CREATE TRIGGER T_CGC_BI_0
  BEFORE INSERT
  ON `cgc`
  FOR EACH ROW
BEGIN 


IF NEW.GEN_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('cgc', 'gen_codice');
END IF;

IF NEW.CEN_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('cgc', 'cen_codice');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
