CREATE TRIGGER T_CLIVEND_BI_0
  BEFORE INSERT
  ON `clivend`
  FOR EACH ROW
BEGIN 


IF NEW.CLI_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('clivend', 'cli_codice');
END IF;

IF NEW.TVEND_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('clivend', 'tvend_codice');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
