CREATE TRIGGER T_CLI_BU_0
  BEFORE UPDATE
  ON `cli`
  FOR EACH ROW
BEGIN 


SET NEW.DESCRIZIONE1 = (SELECT NOM.DESCRIZIONE1 FROM NOM WHERE NOM.CODICE = NEW.CODICE);
SET NEW.DESCRIZIONE2 = (SELECT NOM.DESCRIZIONE2 FROM NOM WHERE NOM.CODICE = NEW.CODICE);
SET NEW.VIA = (SELECT NOM.VIA FROM NOM WHERE NOM.CODICE = NEW.CODICE);
SET NEW.CITTA = (SELECT NOM.CITTA FROM NOM WHERE NOM.CODICE = NEW.CODICE);
SET NEW.PARTITA_IVA = (SELECT NOM.PARTITA_IVA FROM NOM WHERE NOM.CODICE = NEW.CODICE);
SET NEW.CODICE_FISCALE = (SELECT NOM.CODICE_FISCALE FROM NOM WHERE NOM.CODICE = NEW.CODICE);
SET NEW.TNA_CODICE = (SELECT NOM.TNA_CODICE FROM NOM WHERE NOM.CODICE = NEW.CODICE);

IF NEW.TSE_CODICE <> OLD.TSE_CODICE THEN
  SET NEW.DATA_TSE = CURRENT_DATE;
END IF;

END
