CREATE TRIGGER T_CLI_AU
  AFTER UPDATE
  ON `cli`
  FOR EACH ROW
BEGIN 

CALL P_CFG_CLP('U', 'C', NEW.CODICE, concat(trim(NEW.DESCRIZIONE1), ' ', NEW.DESCRIZIONE2), NEW.CITTA, NEW.GEN_CODICE);

IF NEW.OBSOLETO <> OLD.OBSOLETO THEN
  UPDATE IND SET IND.OBSOLETO = NEW.OBSOLETO WHERE IND.CLI_CODICE = NEW.CODICE;
END IF;

END
