CREATE TRIGGER T_CLI_BI_0
  BEFORE INSERT
  ON `cli`
  FOR EACH ROW
BEGIN 


SET NEW.DESCRIZIONE1 = (SELECT NOM.DESCRIZIONE1 FROM NOM WHERE NOM.CODICE = NEW.CODICE);
SET NEW.DESCRIZIONE2 = (SELECT NOM.DESCRIZIONE2 FROM NOM WHERE NOM.CODICE = NEW.CODICE);
SET NEW.VIA = (SELECT NOM.VIA FROM NOM WHERE NOM.CODICE = NEW.CODICE);
SET NEW.CITTA = (SELECT NOM.CITTA FROM NOM WHERE NOM.CODICE = NEW.CODICE);
SET NEW.PARTITA_IVA = (SELECT NOM.PARTITA_IVA FROM NOM WHERE NOM.CODICE = NEW.CODICE);
SET NEW.CODICE_FISCALE = (SELECT NOM.CODICE_FISCALE FROM NOM WHERE NOM.CODICE = NEW.CODICE);
SET NEW.TNA_CODICE = (SELECT NOM.TNA_CODICE FROM NOM WHERE NOM.CODICE = NEW.CODICE);

IF NEW.CODICE = '' THEN
  CALL P_CAMPO_VUOTO('cli', 'codice');
END IF;
IF NEW.TNA_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('cli', 'tna_codice');
END IF;
IF NEW.GEN_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('cli', 'gen_codice');
END IF;
IF NEW.TPA_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('cli', 'tpa_codice');
END IF;
IF NEW.TCC_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('cli', 'tcc_codice');
END IF;
IF NEW.TLV_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('cli', 'tlv_codice');
END IF;
IF NEW.TS1_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('cli', 'ts1_codice');
END IF;
IF NEW.TZO_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('cli', 'tzo_codice');
END IF;
IF NEW.TSC_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('cli', 'tsc_codice');
END IF;
IF NEW.TSP_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('cli', 'tsp_codice');
END IF;
IF NEW.TPO_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('cli', 'tpo_codice');
END IF;
IF NEW.TAR_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('cli', 'tar_codice');
END IF;
IF NEW.TCG_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('cli', 'tcg_codice');
END IF;
IF NEW.TAG_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('cli', 'tag_codice');
END IF;
IF NEW.TP1_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('cli', 'tp1_codice');
END IF;
IF NEW.TPF_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('cli', 'tpf_codice');
END IF;
IF NEW.TST_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('cli', 'tst_codice');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

IF NEW.TSE_CODICE <> '' THEN
  SET NEW.DATA_TSE = CURRENT_DATE;
END IF;

END
