CREATE TRIGGER T_CLITFA_BI_0
  BEFORE INSERT
  ON `clitfa`
  FOR EACH ROW
BEGIN 


IF NEW.CLI_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('clitfa', 'cli_codice');
END IF;

IF NEW.TFA_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('clitfa', 'tfa_codice');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
