CREATE TRIGGER T_CMM_BI_0
  BEFORE INSERT
  ON `cmm`
  FOR EACH ROW
BEGIN 


IF NEW.PROGRESSIVO = 0 THEN
  CALL P_CAMPO_VUOTO('cmm', 'progressivo');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

IF NEW.DATA_COMPETENZA IS NULL THEN
  SET NEW.DATA_COMPETENZA = NEW.DATA_REGISTRAZIONE;
END IF;

END
