CREATE TRIGGER T_CNF_BI_0
  BEFORE INSERT
  ON `cnf`
  FOR EACH ROW
BEGIN 


IF NEW.CONFIGURAZIONE = 0 THEN
  CALL P_CAMPO_VUOTO('cnf', 'configurazione');
END IF;

IF NEW.SEQUENZA = 0 THEN
  CALL P_CAMPO_VUOTO('cnf', 'sequenza');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
