CREATE TRIGGER T_CNL_BI_0
  BEFORE INSERT
  ON `cnl`
  FOR EACH ROW
BEGIN 


IF NEW.CONFIGURAZIONE = 0 THEN
  CALL P_CAMPO_VUOTO('cnl', 'configurazione');
END IF;

IF NEW.SEQUENZA = 0 THEN
  CALL P_CAMPO_VUOTO('cnl', 'sequenza');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
