CREATE TRIGGER T_CPA_BI_0
  BEFORE INSERT
  ON `cpa`
  FOR EACH ROW
BEGIN 


IF NEW.TCF_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('cpa', 'tcf_codice');
END IF;

IF NEW.TAQ_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('cpa', 'taq_codice');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
