CREATE TRIGGER T_CVCMRR_BI_0
  BEFORE INSERT
  ON `cvcmrr`
  FOR EACH ROW
BEGIN 


IF NEW.PROGRESSIVO = 0 THEN
  CALL P_CAMPO_VUOTO('cvcmrr', 'progressivo');
END IF;

IF NEW.RIGA = 0 THEN
  CALL P_CAMPO_VUOTO('cvcmrr', 'riga');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
