CREATE TRIGGER T_DAR_BU_0
  BEFORE UPDATE
  ON `dar`
  FOR EACH ROW
BEGIN 


IF NEW.ART_CODICE <> '' AND NEW.TUM_CODICE = '' THEN
  SET NEW.TUM_CODICE = (SELECT CASE WHEN TUM_CODICE_ACQUISTI = '' THEN TUM_CODICE ELSE TUM_CODICE_ACQUISTI END FROM ART WHERE CODICE = NEW.ART_CODICE);
END IF;

IF NEW.ART_CODICE <> '' THEN
  IF NEW.TUM_QUANTITA_BASE = 0 THEN
	SET NEW.TUM_QUANTITA_BASE = NEW.QUANTITA;
  END IF;
  IF NEW.TUM_QUANTITA_EVASA_BASE = 0 THEN
	SET NEW.TUM_QUANTITA_EVASA_BASE = NEW.QUANTITA_EVASA;
  END IF;
END IF;

END
