CREATE TRIGGER T_F24ALT_BI_0
  BEFORE INSERT
  ON `f24alt`
  FOR EACH ROW
BEGIN 


IF NEW.F24_PROGRESSIVO = 0 THEN
  CALL P_CAMPO_VUOTO('f24alt', 'f24_progressivo');
END IF;

IF NEW.PROGRESSIVO = 0 THEN
  CALL P_CAMPO_VUOTO('f24alt', 'progressivo');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
