CREATE TRIGGER T_FAI_BI_0
  BEFORE INSERT
  ON `fai`
  FOR EACH ROW
BEGIN 


IF NEW.PROGRESSIVO = 0 THEN
  CALL P_CAMPO_VUOTO('fai', 'progressivo');
END IF;

IF NEW.TIV_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('fai', 'tiv_codice');
END IF;

IF NEW.TIPO_MOVIMENTO = '' THEN
  CALL P_CAMPO_VUOTO('fai', 'tipo_movimento');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
