CREATE TRIGGER T_FRN_BI_0
  BEFORE INSERT
  ON `frn`
  FOR EACH ROW
BEGIN 


SET NEW.DESCRIZIONE1 = (SELECT NOM.DESCRIZIONE1 FROM NOM WHERE NOM.CODICE = NEW.CODICE);
SET NEW.DESCRIZIONE2 = (SELECT NOM.DESCRIZIONE2 FROM NOM WHERE NOM.CODICE = NEW.CODICE);
SET NEW.VIA = (SELECT NOM.VIA FROM NOM WHERE NOM.CODICE = NEW.CODICE);
SET NEW.CITTA = (SELECT NOM.CITTA FROM NOM WHERE NOM.CODICE = NEW.CODICE);
SET NEW.PARTITA_IVA = (SELECT NOM.PARTITA_IVA FROM NOM WHERE NOM.CODICE = NEW.CODICE);
SET NEW.CODICE_FISCALE = (SELECT NOM.CODICE_FISCALE FROM NOM WHERE NOM.CODICE = NEW.CODICE);
SET NEW.TNA_CODICE = (SELECT NOM.TNA_CODICE FROM NOM WHERE NOM.CODICE = NEW.CODICE);

IF NEW.CODICE = '' THEN
  CALL P_CAMPO_VUOTO('frn', 'codice');
END IF;
IF NEW.TNA_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('frn', 'tna_codice');
END IF;
IF NEW.GEN_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('frn', 'gen_codice');
END IF;
IF NEW.TPA_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('frn', 'tpa_codice');
END IF;
IF NEW.TCF_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('frn', 'tcf_codice');
END IF;
IF NEW.TLA_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('frn', 'tla_codice');
END IF;
IF NEW.TS2_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('frn', 'ts2_codice');
END IF;
IF NEW.TZO_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('frn', 'tzo_codice');
END IF;
IF NEW.TSC_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('frn', 'tsc_codice');
END IF;
IF NEW.TSP_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('frn', 'tsp_codice');
END IF;
IF NEW.TPO_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('frn', 'tpo_codice');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
