CREATE TRIGGER T_FRD_BI_0
  BEFORE INSERT
  ON `frd`
  FOR EACH ROW
BEGIN 


IF NEW.FRN_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('frd', 'frn_codice');
END IF;

IF NEW.RIFERIMENTO = '' THEN
  CALL P_CAMPO_VUOTO('frd', 'riferimento');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
