CREATE TRIGGER T_FVCMRR_BI_0
  BEFORE INSERT
  ON `fvcmrr`
  FOR EACH ROW
BEGIN 


IF NEW.PROGRESSIVO = 0 THEN
  CALL P_CAMPO_VUOTO('fvcmrr', 'progressivo');
END IF;

IF NEW.RIGA = 0 THEN
  CALL P_CAMPO_VUOTO('fvcmrr', 'riga');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
