CREATE TRIGGER T_FVT_BI_0
  BEFORE INSERT
  ON `fvt`
  FOR EACH ROW
BEGIN 


IF NEW.PROGRESSIVO = 0 THEN
  CALL P_CAMPO_VUOTO('fvt', 'progressivo');
END IF;

IF NEW.CAMBIO = 0 THEN
  CALL P_CAMPO_VUOTO('fvt', 'cambio');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

IF NEW.TIV_CODICE <> '' THEN
	SET NEW.TIV_CODICE_SPESE_BOLLO = NEW.TIV_CODICE;
END IF;

END
