CREATE TRIGGER T_GNG_BI_0
  BEFORE INSERT
  ON `gng`
  FOR EACH ROW
BEGIN 


IF NEW.TGG_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('gng','tgg_codice');
END IF;
IF NEW.NOM_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('gng','nom_codice');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
