CREATE TRIGGER T_GRA_BI_0
  BEFORE INSERT
  ON `gra`
  FOR EACH ROW
BEGIN 


IF NEW.TGR_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('gra','tgr_codice');
END IF;
IF NEW.TAA_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('gra','taa_codice');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
