CREATE TRIGGER T_INF_BI_0
  BEFORE INSERT
  ON `inf`
  FOR EACH ROW
BEGIN 


IF NEW.FRN_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('inf','frn_codice');
END IF;
IF NEW.INDIRIZZO = '' THEN
  CALL P_CAMPO_VUOTO('inf','indirizzo');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
