CREATE TRIGGER T_IND_BI_0
  BEFORE INSERT
  ON `ind`
  FOR EACH ROW
BEGIN 


IF NEW.CLI_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('ind','cli_codice');
END IF;
IF NEW.INDIRIZZO = '' THEN
  CALL P_CAMPO_VUOTO('ind','indirizzo');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
