CREATE TRIGGER T_INV_BI_0
  BEFORE INSERT
  ON `inv`
  FOR EACH ROW
BEGIN 


IF NEW.ART_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('inv','art_codice');
END IF;
IF NEW.TMA_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('inv','tma_codice');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
