CREATE TRIGGER T_IVP_BI_0
  BEFORE INSERT
  ON `ivp`
  FOR EACH ROW
BEGIN 


IF NEW.IVD_PROGRESSIVO = 0 THEN
  CALL P_CAMPO_VUOTO('ivp','ivd_progressivo');
END IF;
IF NEW.RIGA = 0 THEN
  CALL P_CAMPO_VUOTO('ivp','riga');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
