CREATE TRIGGER T_LDA_BI_0
  BEFORE INSERT
  ON `lda`
  FOR EACH ROW
BEGIN 


IF NEW.DATA IS NULL THEN
  CALL P_CAMPO_VUOTO('lda', 'data');
END IF;
IF NEW.PUNTO_VENDITA = '' THEN
  CALL P_CAMPO_VUOTO('lda', 'punto_vendita');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
