CREATE TRIGGER T_LIF_BI_0
  BEFORE INSERT
  ON `lif`
  FOR EACH ROW
BEGIN 


IF NEW.ART_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('lif','art_codice');
END IF;
IF NEW.ESE_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('lif','ese_codice');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
