CREATE TRIGGER T_LIQAI_BI_0
  BEFORE INSERT
  ON `liqai`
  FOR EACH ROW
BEGIN 


IF NEW.ANNO = 0 THEN
  CALL P_CAMPO_VUOTO('liqai','anno');
END IF;
IF NEW.TAI_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('liqai','tai_codice');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
