CREATE TRIGGER T_LOT_BI_0
  BEFORE INSERT
  ON `lot`
  FOR EACH ROW
BEGIN 


IF NEW.ART_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('lot','art_codice');
END IF;
IF NEW.LOTTO = '' THEN
  CALL P_CAMPO_VUOTO('lot','lotto');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
