CREATE TRIGGER T_LSA_BI_0
  BEFORE INSERT
  ON `lsa`
  FOR EACH ROW
BEGIN 


IF NEW.ART_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('lsa','art_codice');
END IF;
IF NEW.TLA_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('lsa','tla_codice');
END IF;
IF NEW.DATA_INIZIO IS NULL THEN
  CALL P_CAMPO_VUOTO('lsa','data_inizio');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
