CREATE TRIGGER T_LSV_BI_0
  BEFORE INSERT
  ON `lsv`
  FOR EACH ROW
BEGIN 


IF NEW.ART_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('lsv', 'art_codice');
END IF;
IF NEW.TLV_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('lsv', 'tlv_codice');
END IF;
IF NEW.DATA_INIZIO IS NULL THEN
  CALL P_CAMPO_VUOTO('lsv', 'data_inizio');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
