CREATE TRIGGER T_LTM_BI_0
  BEFORE INSERT
  ON `ltm`
  FOR EACH ROW
BEGIN 


SET NEW.QUANTITA_ENTRATE = 0;
SET NEW.QUANTITA_USCITE = 0;
IF NEW.ESISTENZA = 'incrementa' THEN
  SET NEW.QUANTITA_ENTRATE = NEW.QUANTITA;
END IF;
IF NEW.ESISTENZA = 'decrementa' THEN
  SET NEW.QUANTITA_USCITE = NEW.QUANTITA;
END IF;

IF NEW.ESISTENZA = 'approntato' THEN
  SET NEW.DOCUMENTO_ORIGINE_APPRONTATO = NEW.DOCUMENTO_ORIGINE;
  SET NEW.DOC_PROGRESSIVO_ORIGINE_APPRONTATO = NEW.DOC_PROGRESSIVO_ORIGINE;
  SET NEW.DOC_RIGA_ORIGINE_APPRONTATO = NEW.DOC_RIGA_ORIGINE;
END IF;

IF NEW.PROGRESSIVO = 0 THEN
  CALL P_CAMPO_VUOTO('ltm', 'progressivo');
END IF;

IF NEW.ART_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('ltm', 'art_codice');
END IF;

IF NEW.LOTTO = '' THEN
  CALL P_CAMPO_VUOTO('ltm', 'lotto');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
