CREATE TRIGGER T_LTM_BU_0
  BEFORE UPDATE
  ON `ltm`
  FOR EACH ROW
BEGIN 


SET NEW.QUANTITA_ENTRATE = 0;
SET NEW.QUANTITA_USCITE = 0;
IF NEW.ESISTENZA = 'incrementa' then
  SET NEW.QUANTITA_ENTRATE = NEW.QUANTITA;
END IF;
IF NEW.ESISTENZA = 'decrementa' then
  SET NEW.QUANTITA_USCITE = NEW.QUANTITA;
END IF;

IF NEW.ESISTENZA = 'approntato' AND OLD.ESISTENZA = 'decrementa' THEN
  SET NEW.DOCUMENTO_ORIGINE = NEW.DOCUMENTO_ORIGINE_APPRONTATO;
  SET NEW.DOC_PROGRESSIVO_ORIGINE = NEW.DOC_PROGRESSIVO_ORIGINE_APPRONTATO;
  SET NEW.DOC_RIGA_ORIGINE = NEW.DOC_RIGA_ORIGINE_APPRONTATO;
END IF;


END
