CREATE TRIGGER T_MACCOSFRN_BI_0
  BEFORE INSERT
  ON maccosfrn
  FOR EACH ROW
BEGIN 


IF NEW.MACINT_PROGRESSIVO = 0 THEN
  CALL P_CAMPO_VUOTO('maccosfrn', 'macint_progressivo');
END IF;

IF NEW.FAR_PROGRESSIVO = 0 THEN
  CALL P_CAMPO_VUOTO('maccosfrn', 'far_progressivo');
END IF;

IF NEW.FAR_RIGA = 0 THEN
  CALL P_CAMPO_VUOTO('maccosfrn', 'far_riga');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
