CREATE TRIGGER T_MAG_BI_0
  BEFORE INSERT
  ON `mag`
  FOR EACH ROW
BEGIN 


IF NEW.ART_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('mag','art_codice');
END IF;
IF NEW.TMA_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('mag','tma_codice');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
