CREATE TRIGGER T_MCS_BI_0
  BEFORE INSERT
  ON `mcs`
  FOR EACH ROW
BEGIN 


IF NEW.CSP_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('mcs','csp_codice');
END IF;
IF NEW.PROGRESSIVO = 0 THEN
  CALL P_CAMPO_VUOTO('mcs','progressivo');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
