CREATE TRIGGER T_MIMA_BI_0
  BEFORE INSERT
  ON `mima`
  FOR EACH ROW
BEGIN 


IF NEW.PROGRESSIVO = 0 THEN
  CALL P_CAMPO_VUOTO('mima', 'progressivo');
END IF;

IF NEW.TIPO_DOCUMENTO = 'nota credito' THEN
  SET NEW.SEGNO = -1;
ELSE
  SET NEW.SEGNO = 1;
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
