CREATE TRIGGER T_MMT_BI_0
  BEFORE INSERT
  ON `mmt`
  FOR EACH ROW
BEGIN 


IF NEW.PROGRESSIVO = 0 THEN
  CALL P_CAMPO_VUOTO('mmt','progressivo');
END IF;

IF NEW.DATA_REGISTRAZIONE IS NULL THEN
  CALL P_CAMPO_VUOTO('mmt','data_registrazione');
END IF;

IF NEW.TIPO_MOVIMENTO = '' THEN
  CALL P_CAMPO_VUOTO('mmt','tipo_movimento');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
