CREATE TRIGGER T_MMR_BU_0
  BEFORE UPDATE
  ON mmr
  FOR EACH ROW
BEGIN 


IF NEW.QUANTITA_ENTRATE = 0 AND NEW.QUANTITA_USCITE = 0 AND NEW.QUANTITA <> 0 THEN
  IF (SELECT TMO.ESISTENZA FROM MMT INNER JOIN TMO ON TMO.CODICE = MMT.TMO_CODICE WHERE MMT.PROGRESSIVO = NEW.PROGRESSIVO) <> 'ignora' THEN
	CALL P_CAMPO_VUOTO('mmr','quantita_entrate - quantita_uscite');
  END IF;
END IF;

END
