CREATE TRIGGER T_NAA_BI_0
  BEFORE INSERT
  ON `naa`
  FOR EACH ROW
BEGIN 


IF NEW.NOM_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('naa','nom_codice');
END IF;
IF NEW.TAA_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('naa','taa_codice');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
