CREATE TRIGGER T_NCP_BI_0
  BEFORE INSERT
  ON `ncp`
  FOR EACH ROW
BEGIN 


IF NEW.NOM_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('ncp','nom_codice');
END IF;
IF NEW.CPC_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('ncp','cpc_codice');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
