CREATE TRIGGER T_NGI_BI_0
  BEFORE INSERT
  ON `ngi`
  FOR EACH ROW
BEGIN 


IF NEW.PROGRESSIVO = 0 THEN
  CALL P_CAMPO_VUOTO('ngi','progressivo');
END IF;
IF NEW.TIV_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('ngi','tiv_codice');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
