CREATE TRIGGER T_NMD_BI_0
  BEFORE INSERT
  ON `nmd`
  FOR EACH ROW
BEGIN 


IF NEW.NOM_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('nmd','nom_codice');
END IF;
IF NEW.DATA_FINE IS NULL THEN
  CALL P_CAMPO_VUOTO('nmd','data_fine');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
