CREATE TRIGGER T_NML_BI_0
  BEFORE INSERT
  ON `nml`
  FOR EACH ROW
BEGIN 


IF NEW.NOM_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('nml','nom_codice');
END IF;
IF NEW.DESCRIZIONE = '' THEN
  CALL P_CAMPO_VUOTO('nml','descrizione');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
