CREATE TRIGGER T_NOMTGM23_BI_0
  BEFORE INSERT
  ON `nomtgm23`
  FOR EACH ROW
BEGIN 


IF NEW.NOM_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('nomtgm23', 'nom_codice');
END IF;
IF NEW.TGM_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('nomtgm23', 'tgm_codice');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
