CREATE TRIGGER T_NOMTCM23_BI_0
  BEFORE INSERT
  ON `nomtcm23`
  FOR EACH ROW
BEGIN 


IF NEW.NOM_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('nomtcm23', 'nom_codice');
END IF;
IF NEW.TCM_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('nomtcm23', 'tcm_codice');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
