CREATE TRIGGER T_NSL_BI_0
  BEFORE INSERT
  ON `nsl`
  FOR EACH ROW
BEGIN 


IF NEW.TNL_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('nsl','tnl_codice');
END IF;
IF NEW.NUMERO_SOLLECITO = 0 THEN
  CALL P_CAMPO_VUOTO('nsl','numero_sollecito');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
