CREATE TRIGGER T_OAP_BI_0
  BEFORE INSERT
  ON `oap`
  FOR EACH ROW
BEGIN 


IF NEW.PROGRESSIVO = 0 THEN
  CALL P_CAMPO_VUOTO('oap','progressivo');
END IF;
IF NEW.RATA = 0 THEN
  CALL P_CAMPO_VUOTO('oap','rata');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
