CREATE TRIGGER T_OAD_BI_0
  BEFORE INSERT
  ON `oad`
  FOR EACH ROW
BEGIN 


IF NEW.PROGRESSIVO = 0 THEN
  CALL P_CAMPO_VUOTO('oad','progressivo');
END IF;
IF NEW.RIGA = 0  THEN
  CALL P_CAMPO_VUOTO('oad','riga');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
