CREATE TRIGGER T_OAR_BI_0
  BEFORE INSERT
  ON `oar`
  FOR EACH ROW
BEGIN 


IF NEW.PROGRESSIVO = 0 THEN
  CALL P_CAMPO_VUOTO('oar','progressivo');
END IF;
IF NEW.RIGA = 0 THEN
  CALL P_CAMPO_VUOTO('oar','riga');
END IF;

IF NEW.ART_CODICE <> '' AND NEW.TUM_CODICE = '' THEN
  SET NEW.TUM_CODICE = (SELECT CASE WHEN TUM_CODICE_ACQUISTI = '' THEN TUM_CODICE ELSE TUM_CODICE_ACQUISTI END FROM ART WHERE CODICE = NEW.ART_CODICE);
END IF;

IF NEW.ART_CODICE <> '' THEN
  IF NEW.TUM_QUANTITA_BASE = 0 THEN
	SET NEW.TUM_QUANTITA_BASE = NEW.QUANTITA;
  END IF;
  IF NEW.TUM_QUANTITA_EVASA_BASE = 0 THEN
	SET NEW.TUM_QUANTITA_EVASA_BASE = NEW.QUANTITA_EVASA;
  END IF;
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
