CREATE TRIGGER T_OPT_BI_0
  BEFORE INSERT
  ON `opt`
  FOR EACH ROW
BEGIN 


IF NEW.ART_CODICE_FINITO = '' THEN
  SET NEW.ART_CODICE_FINITO = NEW.ART_CODICE;
END IF;

IF NEW.PROGRESSIVO_FINITO = 0 THEN
  SET NEW.PROGRESSIVO_FINITO = NEW.PROGRESSIVO;
END IF;

IF NEW.PROGRESSIVO = 0 THEN
  CALL P_CAMPO_VUOTO('opt','progressivo');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
