CREATE TRIGGER T_OPC_BI_0
  BEFORE INSERT
  ON `opc`
  FOR EACH ROW
BEGIN 


IF NEW.PROGRESSIVO = 0 THEN
  CALL P_CAMPO_VUOTO('opc', 'progressivo');
END IF;
IF NEW.FAS_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('opc', 'fas_codice');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
