CREATE TRIGGER T_ORS_AU
  AFTER UPDATE
  ON `ors`
  FOR EACH ROW
BEGIN 

CALL P_ORS_ORE
(NEW.CODICE_SSCC, (NEW.QUANTITA_CARICO - OLD.QUANTITA_CARICO) - (NEW.QUANTITA_SCARICO - OLD.QUANTITA_SCARICO));

END
