CREATE TRIGGER T_ORD_BI_0
  BEFORE INSERT
  ON `ord`
  FOR EACH ROW
BEGIN 


IF NEW.PROGRESSIVO = 0 THEN
  CALL P_CAMPO_VUOTO('ord','progressivo');
END IF;
IF NEW.RIGA = 0 THEN
  CALL P_CAMPO_VUOTO('ord','riga');
END IF;
IF NEW.RIGA_DETTAGLIO = 0 THEN
  CALL P_CAMPO_VUOTO('ord','riga_dettaglio');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
