CREATE TRIGGER T_ORM_BI_0
  BEFORE INSERT
  ON `orm`
  FOR EACH ROW
BEGIN 


IF NEW.PROGRESSIVO = 0 THEN
  CALL P_CAMPO_VUOTO('orm','progressivo');
END IF;
IF NEW.RIGA = 0 THEN
  CALL P_CAMPO_VUOTO('orm','riga');
END IF;
IF NEW.RIGA_ORM = 0 THEN
  CALL P_CAMPO_VUOTO('orm','riga_orm');
END IF;
IF NEW.RIGA_ORD = 0 THEN
  CALL P_CAMPO_VUOTO('orm','riga_ord');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
