CREATE TRIGGER T_ORE_BI_0
  BEFORE INSERT
  ON `ore`
  FOR EACH ROW
BEGIN 


IF NEW.PROGRESSIVO = 0 THEN
  CALL P_CAMPO_VUOTO('ore','progressivo');
END IF;
IF NEW.RIGA = 0 THEN
  CALL P_CAMPO_VUOTO('ore','riga');
END IF;
IF NEW.RIGA_DETTAGLIO = 0 THEN
  CALL P_CAMPO_VUOTO('ore','riga_dettaglio');
END IF;
IF NEW.RIGA_ORE = 0 THEN
  CALL P_CAMPO_VUOTO('ore','riga_ore');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
