CREATE TRIGGER T_ORF_BI_0
  BEFORE INSERT
  ON `orf`
  FOR EACH ROW
BEGIN 


IF NEW.PROGRESSIVO = 0 THEN
  CALL P_CAMPO_VUOTO('orf','progressivo');
END IF;
IF NEW.RIGA = 0 THEN
  CALL P_CAMPO_VUOTO('orf','riga');
END IF;
IF NEW.RIGA_DETTAGLIO = 0 THEN
  CALL P_CAMPO_VUOTO('orf','riga_dettaglio');
END IF;
IF NEW.RIGA_ORF = 0 THEN
  CALL P_CAMPO_VUOTO('orf','riga_orf');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
