CREATE TRIGGER T_OVP_BI_0
  BEFORE INSERT
  ON `ovp`
  FOR EACH ROW
BEGIN 


IF NEW.PROGRESSIVO = 0 THEN
  CALL P_CAMPO_VUOTO('ovp','progressivo');
END IF;
IF NEW.RATA = 0 THEN
  CALL P_CAMPO_VUOTO('ovp','rata');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
