CREATE TRIGGER T_PAT_BI_0
  BEFORE INSERT
  ON `pat`
  FOR EACH ROW
BEGIN 


SET NEW.IMPORTO_SALDO = NEW.IMPORTO_DOVUTO - NEW.IMPORTO_PAGATO;

IF NEW.PROGRESSIVO = 0 THEN
  CALL P_CAMPO_VUOTO('pat','progressivo');
END IF;

IF NEW.PAT_PROGRESSIVO = 0 THEN
  SET NEW.PAT_PROGRESSIVO = NEW.PROGRESSIVO;
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
