CREATE TRIGGER T_PAD_BI_0
  BEFORE INSERT
  ON `pad`
  FOR EACH ROW
BEGIN 


IF NEW.PROGRESSIVO = 0 THEN
  CALL P_CAMPO_VUOTO('pad','progressivo');
END IF;
IF NEW.RIGA = 0  THEN
  CALL P_CAMPO_VUOTO('pad','riga');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
