CREATE TRIGGER T_PAS_AU
  AFTER UPDATE
  ON `pas`
  FOR EACH ROW
BEGIN 

if old.IMPORTO_PAGATO <> new.IMPORTO_PAGATO
or old.IMPORTO_PAGATO_EURO <> new.IMPORTO_PAGATO_EURO then

  CALL P_PAS_PAT (NEW.PROGRESSIVO, NEW.IMPORTO_PAGATO - OLD.IMPORTO_PAGATO, NEW.IMPORTO_PAGATO_EURO - OLD.IMPORTO_PAGATO_EURO);

end if;

END
