CREATE TRIGGER T_PAS_BI_0
  BEFORE INSERT
  ON `pas`
  FOR EACH ROW
BEGIN 


IF NEW.PROGRESSIVO = 0 THEN
  CALL P_CAMPO_VUOTO('pas','progressivo');
END IF;
IF NEW.RIGA = 0 THEN
  CALL P_CAMPO_VUOTO('pas','riga');
END IF;

IF NEW.DATA_DOCUMENTO IS NULL THEN
  SET NEW.DATA_DOCUMENTO = NEW.DATA_REGISTRAZIONE;
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
