CREATE TRIGGER T_PCS_BI_0
  BEFORE INSERT
  ON `pcs`
  FOR EACH ROW
BEGIN 


IF NEW.ESE_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('pcs','ese_codice');
END IF;
IF NEW.CSP_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('pcs','csp_codice');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
