CREATE TRIGGER T_PCL_BI_0
  BEFORE INSERT
  ON `pcl`
  FOR EACH ROW
BEGIN 


IF NEW.ESE_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('pcl','ese_codice');
END IF;
IF NEW.TCL_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('pcl','tcl_codice');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
