CREATE TRIGGER T_PERCU_BI_0
  BEFORE INSERT
  ON percu
  FOR EACH ROW
BEGIN 


IF NEW.PROGRESSIVO = 0 THEN
  CALL P_CAMPO_VUOTO('percu', 'progressivo');
END IF;

IF NEW.FRN_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('percu', 'frn_codice');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
