CREATE TRIGGER T_PNR_AU 
AFTER UPDATE ON PNR FOR EACH ROW 
BEGIN 

if old.IMPORTO_DARE <> new.IMPORTO_DARE
or old.IMPORTO_DARE_EURO <> new.IMPORTO_DARE_EURO
or old.IMPORTO_AVERE <> new.IMPORTO_AVERE
or old.IMPORTO_AVERE_EURO <> new.IMPORTO_AVERE_EURO then

  CALL p_pnr_pnt (OLD.PROGRESSIVO, NEW.IMPORTO_DARE - OLD.IMPORTO_DARE, NEW.IMPORTO_DARE_EURO - OLD.IMPORTO_DARE_EURO, 
	NEW.IMPORTO_AVERE - OLD.IMPORTO_AVERE, NEW.IMPORTO_AVERE_EURO - OLD.IMPORTO_AVERE_EURO);

end if;

if old.CFG_TIPO <> new.CFG_TIPO
or old.CFG_CODICE <> new.CFG_CODICE
or old.PARTITE <> new.PARTITE
or old.IMPORTO_DARE_EURO <> new.IMPORTO_DARE_EURO
or old.IMPORTO_AVERE_EURO <> new.IMPORTO_AVERE_EURO
or old.IMPORTO_DARE <> new.IMPORTO_DARE
or old.IMPORTO_AVERE <> new.IMPORTO_AVERE
or old.PROGRESSIVO <> new.PROGRESSIVO then

  CALL p_pnr_cfg ('U', OLD.PROGRESSIVO, OLD.CFG_TIPO, OLD.CFG_CODICE, OLD.PARTITE, OLD.IMPORTO_DARE_EURO, OLD.IMPORTO_AVERE_EURO,
	OLD.IMPORTO_DARE, OLD.IMPORTO_AVERE,
	NEW.PROGRESSIVO, NEW.CFG_TIPO, NEW.CFG_CODICE, NEW.PARTITE, NEW.IMPORTO_DARE_EURO, NEW.IMPORTO_AVERE_EURO,
	NEW.IMPORTO_DARE, NEW.IMPORTO_AVERE);

end if;

END
