CREATE TRIGGER T_PNR_BI_0
  BEFORE INSERT
  ON `pnr`
  FOR EACH ROW
BEGIN 


IF NEW.PROGRESSIVO = 0 THEN
  CALL P_CAMPO_VUOTO('pnr','progressivo');
END IF;
IF NEW.RIGA = 0 THEN
  CALL P_CAMPO_VUOTO('pnr','riga');
END IF;

IF (NEW.CFG_TIPO = 'C' AND NOT EXISTS(SELECT ID FROM CLI WHERE CODICE = NEW.CFG_CODICE)) OR
	(NEW.CFG_TIPO = 'F' AND NOT EXISTS(SELECT ID FROM FRN WHERE CODICE = NEW.CFG_CODICE)) OR
	(NEW.CFG_TIPO = 'G' AND NOT EXISTS(SELECT ID FROM GEN WHERE CODICE = NEW.CFG_CODICE)) THEN
  CALL P_CAMPO_VUOTO('pnr',concat('sottoconto ', NEW.CFG_TIPO, ' ', NEW.CFG_CODICE));
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
