CREATE TRIGGER T_PNR_BU_0
  BEFORE UPDATE
  ON `pnr`
  FOR EACH ROW
BEGIN 


IF (NEW.CFG_TIPO = 'C' AND NOT EXISTS(SELECT ID FROM CLI WHERE CODICE = NEW.CFG_CODICE)) OR
	(NEW.CFG_TIPO = 'F' AND NOT EXISTS(SELECT ID FROM FRN WHERE CODICE = NEW.CFG_CODICE)) OR
	(NEW.CFG_TIPO = 'G' AND NOT EXISTS(SELECT ID FROM GEN WHERE CODICE = NEW.CFG_CODICE)) THEN
  CALL P_CAMPO_VUOTO('pnr',concat('sottoconto ', NEW.CFG_TIPO, ' ', NEW.CFG_CODICE));
END IF;

END
