CREATE TRIGGER T_PNT_BD
  BEFORE DELETE
  ON `pnt`
  FOR EACH ROW
BEGIN 

CALL P_ENASARCO(old.progressivo);

DELETE FROM NTR WHERE EXISTS(SELECT ID FROM NTT WHERE PROGRESSIVO = NTR.PROGRESSIVO AND NTT.DOCUMENTO_ORIGINE = 'primanota contabilita' AND DOC_PROGRESSIVO_ORIGINE = old.progressivo);
DELETE FROM NTT WHERE NTT.DOCUMENTO_ORIGINE = 'primanota contabilita' AND DOC_PROGRESSIVO_ORIGINE = old.progressivo;


END
