CREATE TRIGGER T_PNR_AI 
AFTER INSERT ON PNR FOR EACH ROW 
BEGIN 

CALL p_pnr_pnt 
(NEW.PROGRESSIVO,
NEW.IMPORTO_DARE,
NEW.IMPORTO_DARE_EURO,
NEW.IMPORTO_AVERE,
NEW.IMPORTO_AVERE_EURO);

CALL p_pnr_cfg 
('I', 0, '', '', '', 0, 0, 0, 0,
NEW.PROGRESSIVO,
NEW.CFG_TIPO, 
NEW.CFG_CODICE,
NEW.PARTITE,
NEW.IMPORTO_DARE_EURO,
NEW.IMPORTO_AVERE_EURO,
NEW.IMPORTO_DARE,
NEW.IMPORTO_AVERE);

END
