CREATE TRIGGER T_PNT_BI_0
  BEFORE INSERT
  ON `pnt`
  FOR EACH ROW
BEGIN 


IF NEW.PROGRESSIVO = 0 THEN
  CALL P_CAMPO_VUOTO('pnt','progressivo');
END IF;

IF NEW.DATA_REGISTRAZIONE IS NULL THEN
  CALL P_CAMPO_VUOTO('pnt','data_registrazione');
END IF;

IF NEW.IVA_SOSPENSIONE IS NULL OR NEW.IVA_SOSPENSIONE = '' THEN
  CALL P_CAMPO_VUOTO('pnt','iva_sospensione');
END IF;

IF NEW.TIPO_MOVIMENTO = '' THEN
  CALL P_CAMPO_VUOTO('pnt','tipo_movimento');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
