CREATE TRIGGER T_PNI_AU 
AFTER UPDATE ON PNI FOR EACH ROW 
BEGIN 

if old.IMPORTO_IMPONIBILE <> new.IMPORTO_IMPONIBILE
or old.IMPORTO_IMPONIBILE_EURO <> new.IMPORTO_IMPONIBILE_EURO
or old.IMPORTO_IVA <> new.IMPORTO_IVA
or old.IMPORTO_IVA_EURO <> new.IMPORTO_IVA_EURO
or old.IMPORTO_INDETRAIBILE <> new.IMPORTO_INDETRAIBILE
or old.IMPORTO_INDETRAIBILE_EURO <> new.IMPORTO_INDETRAIBILE_EURO then

  CALL p_pni_pnt (NEW.PROGRESSIVO,
	NEW.IMPORTO_IMPONIBILE - OLD.IMPORTO_IMPONIBILE, NEW.IMPORTO_IMPONIBILE_EURO - OLD.IMPORTO_IMPONIBILE_EURO,
	NEW.IMPORTO_IVA - OLD.IMPORTO_IVA, NEW.IMPORTO_IVA_EURO - OLD.IMPORTO_IVA_EURO,
	NEW.IMPORTO_INDETRAIBILE - OLD.IMPORTO_INDETRAIBILE, NEW.IMPORTO_INDETRAIBILE_EURO - OLD.IMPORTO_INDETRAIBILE_EURO);

end if;

END

