CREATE TRIGGER T_PNI_BD 
BEFORE DELETE ON PNI FOR EACH ROW 
BEGIN 

CALL p_pni_pnt (OLD.PROGRESSIVO, 
OLD.IMPORTO_IMPONIBILE * -1, 
OLD.IMPORTO_IMPONIBILE_EURO * -1, 
OLD.IMPORTO_IVA * -1, 
OLD.IMPORTO_IVA_EURO * -1, 
OLD.IMPORTO_INDETRAIBILE * -1, 
OLD.IMPORTO_INDETRAIBILE_EURO * -1);
END

