CREATE TRIGGER T_PNI_AI 
AFTER INSERT ON PNI FOR EACH ROW 
BEGIN 

CALL p_pni_pnt 
(NEW.PROGRESSIVO,
NEW.IMPORTO_IMPONIBILE,
NEW.IMPORTO_IMPONIBILE_EURO,
NEW.IMPORTO_IVA,
NEW.IMPORTO_IVA_EURO,
NEW.IMPORTO_INDETRAIBILE,
NEW.IMPORTO_INDETRAIBILE_EURO);

END
