CREATE TRIGGER T_PRO_BI_0
  BEFORE INSERT
  ON `pro`
  FOR EACH ROW
BEGIN 


IF NEW.TAG_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('pro', 'tag_codice');
END IF;
IF NEW.DATA_DOCUMENTO IS NULL THEN
  CALL P_CAMPO_VUOTO('pro', 'data_documento');
END IF;
IF NEW.NUMERO_DOCUMENTO = 0 THEN
  CALL P_CAMPO_VUOTO('pro', 'numero_documento');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
