CREATE TRIGGER T_PRC_BI_0
  BEFORE INSERT
  ON `prc`
  FOR EACH ROW
BEGIN 


IF NEW.TRC_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('prc', 'trc_codice');
END IF;
IF NEW.CODICE_01 = '' THEN
  CALL P_CAMPO_VUOTO('prc', 'codice_01');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
