CREATE TRIGGER T_PTI_BI_0
  BEFORE INSERT
  ON `pti`
  FOR EACH ROW
BEGIN 


SET NEW.IMPORTO_DISPONIBILE = NEW.IMPORTO - NEW.IMPORTO_UTILIZZATO;

IF NEW.CLI_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('pti','cli_codice');
END IF;
IF NEW.DATA_INIZIO IS NULL THEN
  CALL P_CAMPO_VUOTO('pti','data_inizio');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
