CREATE TRIGGER T_PVT_BI_0
  BEFORE INSERT
  ON `pvt`
  FOR EACH ROW
BEGIN 


IF NEW.PROGRESSIVO = 0  THEN
  CALL P_CAMPO_VUOTO('pvt','progressivo');
END IF;

IF NEW.CAMBIO = 0 THEN
  CALL P_CAMPO_VUOTO('pvt', 'cambio');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

SET NEW.DATA_COMPETENZA_IVA = NULL;

IF NEW.TIV_CODICE <> '' THEN
	SET NEW.TIV_CODICE_SPESE_BOLLO = NEW.TIV_CODICE;
END IF;

END
