CREATE TRIGGER T_PVP_BI_0
  BEFORE INSERT
  ON `pvp`
  FOR EACH ROW
BEGIN 


IF NEW.PROGRESSIVO = 0 THEN
  CALL P_CAMPO_VUOTO('pvp','progressivo');
END IF;
IF NEW.RATA = 0 THEN
  CALL P_CAMPO_VUOTO('pvp','rata');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
