CREATE TRIGGER T_PVR_BI_0
  BEFORE INSERT
  ON `pvr`
  FOR EACH ROW
BEGIN 

DECLARE D_TUM_CODICE_VENDITE				VARCHAR(04);
DECLARE D_TUM_COEFFICIENTE_VENDITE			NUMERIC(18,6);
DECLARE D_OPERAZIONE_COEFFICIENTE_VEN		CHAR(01);


IF NEW.ART_CODICE <> '' AND NEW.TIPO_MOVIMENTO = 'sconto merce' AND
(SELECT TIV_CODICE_SCONTO_MERCE FROM ARC.DIT03 WHERE CODICE = @DIT_CODICE) <> '' THEN
  SET NEW.TIV_CODICE = (SELECT TIV_CODICE_SCONTO_MERCE FROM ARC.DIT03 WHERE CODICE = @DIT_CODICE);
END IF;

IF NEW.SEQUENZA = 0 THEN
  SET NEW.SEQUENZA = NEW.RIGA;
END IF;

IF NEW.PROGRESSIVO = 0 THEN
  CALL P_CAMPO_VUOTO('pvr','progressivo');
END IF;

IF NEW.RIGA = 0 THEN
  CALL P_CAMPO_VUOTO('pvr','riga');
END IF;

IF NEW.ART_CODICE <> '' AND NEW.TUM_CODICE = '' THEN
  SET NEW.TUM_CODICE = (SELECT CASE WHEN TUM_CODICE_VENDITE = '' THEN TUM_CODICE ELSE TUM_CODICE_VENDITE END FROM ART WHERE CODICE = NEW.ART_CODICE);
END IF;

IF NEW.ART_CODICE <> '' THEN
  IF NEW.TUM_QUANTITA_BASE = 0 THEN
	SET NEW.TUM_QUANTITA_BASE = NEW.QUANTITA;
  END IF;
  IF NEW.TUM_QUANTITA_EVASA_BASE = 0 THEN
	SET NEW.TUM_QUANTITA_EVASA_BASE = NEW.QUANTITA_EVASA;
  END IF;
  IF NEW.TUM_QUANTITA_APPRONTATA_BASE = 0 THEN
	SET NEW.TUM_QUANTITA_APPRONTATA_BASE = NEW.QUANTITA_APPRONTATA;
  END IF;
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
