CREATE TRIGGER T_PVI_BI_0
  BEFORE INSERT
  ON `pvi`
  FOR EACH ROW
BEGIN 


IF NEW.PROGRESSIVO = 0 THEN
  CALL P_CAMPO_VUOTO('pvi','progressivo');
END IF;
IF NEW.TIV_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('pvi','tiv_codice');
END IF;
IF NEW.TIPO_MOVIMENTO = '' THEN
  CALL P_CAMPO_VUOTO('pvi','tipo_movimento');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
