CREATE TRIGGER T_RAI_BI_0
  BEFORE INSERT
  ON `rai`
  FOR EACH ROW
BEGIN 


IF NEW.PROGRESSIVO = 0 THEN
  CALL P_CAMPO_VUOTO('rai','progressivo');
END IF;
IF NEW.TIV_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('rai','tiv_codice');
END IF;
IF NEW.TIPO_MOVIMENTO = '' THEN
  CALL P_CAMPO_VUOTO('rai','tipo_movimento');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
