CREATE TRIGGER T_RAP_BI_0
  BEFORE INSERT
  ON `rap`
  FOR EACH ROW
BEGIN 


IF NEW.PROGRESSIVO = 0 THEN
  CALL P_CAMPO_VUOTO('rap','progressivo');
END IF;
IF NEW.RATA = 0 THEN
  CALL P_CAMPO_VUOTO('rap','rata');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
