CREATE TRIGGER T_RAR_BU_0
  BEFORE UPDATE
  ON `rar`
  FOR EACH ROW
BEGIN 


IF NEW.ART_CODICE <> '' AND NEW.TUM_CODICE = '' THEN
  SET NEW.TUM_CODICE = (SELECT CASE WHEN TUM_CODICE_ACQUISTI = '' THEN TUM_CODICE ELSE TUM_CODICE_ACQUISTI END FROM ART WHERE CODICE = NEW.ART_CODICE);
END IF;

IF NEW.ART_CODICE <> '' THEN
  IF NEW.TUM_QUANTITA_BASE = 0 THEN
	SET NEW.TUM_QUANTITA_BASE = NEW.QUANTITA;
  END IF;
  IF NEW.TUM_QUANTITA_EVASA_BASE = 0 THEN
	SET NEW.TUM_QUANTITA_EVASA_BASE = NEW.QUANTITA_EVASA;
  END IF;
END IF;

/*
IF NEW.SITUAZIONE = 'annullato' AND NEW.DOCUMENTO_ORIGINE = 'rda' THEN
  IF NOT EXISTS(SELECT ID FROM RAR WHERE PROGRESSIVO <> NEW.PROGRESSIVO AND RIGA <> NEW.RIGA AND
      DOCUMENTO_ORIGINE = NEW.DOCUMENTO_ORIGINE AND DOC_PROGRESSIVO_ORIGINE = NEW.DOC_PROGRESSIVO_ORIGINE AND
      SITUAZIONE <> 'annullato') THEN
  	DELETE FROM RAR WHERE PROGRESSIVO = NEW.DOC_PROGRESSIVO_ORIGINE;
  END IF;
END IF;
*/

END
