CREATE TRIGGER T_RCR_BI_0
  BEFORE INSERT
  ON `rcr`
  FOR EACH ROW
BEGIN 


IF NEW.PROGRESSIVO = 0 THEN
  CALL P_CAMPO_VUOTO('rcr','progressivo');
END IF;
IF NEW.RIGA = 0 THEN
  CALL P_CAMPO_VUOTO('rcr','riga');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
