CREATE TRIGGER T_RDO_BI_0
  BEFORE INSERT
  ON `rdo`
  FOR EACH ROW
BEGIN 


IF NEW.PROGRESSIVO = 0 THEN
  CALL P_CAMPO_VUOTO('rdo','progressivo');
END IF;
IF NEW.FRN_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('rdo','frn_codice');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
