CREATE TRIGGER T_RIPCT_BI_0
  BEFORE INSERT
  ON `ripct`
  FOR EACH ROW
BEGIN 


IF NEW.PROGRESSIVO = 0 THEN
  CALL P_CAMPO_VUOTO('ripct', 'progressivo');
END IF;

IF NEW.CLI_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('ripct', 'cli_codice');
END IF;

IF NEW.ART_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('ripct', 'art_codice');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
