CREATE TRIGGER T_SCF_BI_0
  BEFORE INSERT
  ON `scf`
  FOR EACH ROW
BEGIN 


IF NEW.DIT_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('scf','dit_codice');
END IF;
IF NEW.GEN_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('scf','gen_codice');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
