CREATE TRIGGER T_SDR_BI_0
  BEFORE INSERT
  ON `sdr`
  FOR EACH ROW
BEGIN 


IF NEW.PROGRESSIVO = 0 THEN
  CALL P_CAMPO_VUOTO('sdr','progressivo');
END IF;
IF NEW.RIGA = 0 THEN
  CALL P_CAMPO_VUOTO('sdr','riga');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
