CREATE TRIGGER T_SLR_BI_0
  BEFORE INSERT
  ON `slr`
  FOR EACH ROW
BEGIN 


IF NEW.SLT_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('slr','slt_codice');
END IF;
IF NEW.TCH_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('slr','tch_codice');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
