CREATE TRIGGER T_STA_BI_0
  BEFORE INSERT
  ON `sta`
  FOR EACH ROW
BEGIN 


IF NEW.FRN_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('sta','frn_codice');
END IF;
IF NEW.ART_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('sta','art_codice');
END IF;
IF NEW.ANNO = 0 THEN
  CALL P_CAMPO_VUOTO('sta','anno');
END IF;
IF NEW.MESE = 0 THEN
  CALL P_CAMPO_VUOTO('sta','mese');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
