CREATE TRIGGER T_TBO_BI_0
  BEFORE INSERT
  ON `tbo`
  FOR EACH ROW
BEGIN 


IF NEW.TVA_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('tbo','tva_codice');
END IF;
IF NEW.DATA_INIZIO IS NULL THEN
  CALL P_CAMPO_VUOTO('tbo','data_inizio');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
