CREATE TRIGGER T_TCHCOS_BI_0
  BEFORE INSERT
  ON `tchcos`
  FOR EACH ROW
BEGIN 


IF NEW.TCH_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('tchcos','tch_codice');
END IF;

IF NEW.DATA_INIZIO IS NULL THEN
  CALL P_CAMPO_VUOTO('tchcos', 'data_inizio');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
