CREATE TRIGGER T_TCU_BI_0
  BEFORE INSERT
  ON `tcu`
  FOR EACH ROW
BEGIN 


IF NEW.TCI_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('tcu','tci_codice');
END IF;
IF NEW.TCU_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('tcu','tcu_codice');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
