CREATE TRIGGER T_TCZ_BI_0
  BEFORE INSERT
  ON `tcz`
  FOR EACH ROW
BEGIN 


IF NEW.TEC_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('tcz','tec_codice');
END IF;
IF NEW.TZO_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('tcz','tzo_codice');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
