CREATE TRIGGER T_TCO_BI_0
  BEFORE INSERT
  ON `tco`
  FOR EACH ROW
BEGIN 


IF NEW.CODICE = '' THEN
  CALL P_CAMPO_VUOTO('tco','codice');
END IF;

IF NEW.GEN_CODICE_IVA <> '' AND (NEW.CFG_TIPO_02 = '' OR NEW.CFG_CODICE_02 = '' OR NEW.CFG_DARE_AVERE_02 = '') THEN
  SET NEW.CFG_TIPO_02 = 'G';
  SET NEW.CFG_CODICE_02 = NEW.GEN_CODICE_IVA;
  IF NEW.TIPO_REGISTRO_IVA = 'acquisti' THEN
    SET NEW.CFG_DARE_AVERE_02 = 'D';
  ELSE
    SET NEW.CFG_DARE_AVERE_02 = 'A';
  END IF;  
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
