CREATE TRIGGER T_TDC_BI_0
  BEFORE INSERT
  ON `tdc`
  FOR EACH ROW
BEGIN 


IF NEW.TCI_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('tdc','tci_codice');
END IF;
IF NEW.CODICE = '' THEN
  CALL P_CAMPO_VUOTO('tdc','codice');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
