CREATE TRIGGER T_TDESCPEC_BI_0
  BEFORE INSERT
  ON TDESCPEC
  FOR EACH ROW
BEGIN 


IF NEW.TCPEC_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('tdescpec','tcpec_codice');
END IF;

IF NEW.CODICE = '' THEN
  CALL P_CAMPO_VUOTO('tdescpec','codice');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
