CREATE TRIGGER T_TR3_BI_0
  BEFORE INSERT
  ON `tr3`
  FOR EACH ROW
BEGIN 


IF NEW.CLI_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('tr3','cli_codice');
END IF;
IF NEW.TR1_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('tr3','tr1_codice');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
