CREATE TRIGGER T_TRF_BI_0
  BEFORE INSERT
  ON `trf`
  FOR EACH ROW
BEGIN 


IF NEW.ANNO = '' THEN
  CALL P_CAMPO_VUOTO('trf', 'anno');
END IF;
IF NEW.TIPO_REGISTRO = '' THEN
  CALL P_CAMPO_VUOTO('trf', 'tipo_registro');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
