CREATE TRIGGER T_TR2_BI_0
  BEFORE INSERT
  ON `tr2`
  FOR EACH ROW
BEGIN 


IF NEW.ART_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('tr2','art_codice');
END IF;
IF NEW.TR1_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('tr2','tr1_codice');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
