CREATE TRIGGER T_TSS_BI_0
  BEFORE INSERT
  ON `tss`
  FOR EACH ROW
BEGIN 


IF NEW.TSP_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('tss','tsp_codice');
END IF;
IF NEW.DATA IS NULL THEN
  CALL P_CAMPO_VUOTO('tss','data');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
