CREATE TRIGGER T_TSI_BI_0
  BEFORE INSERT
  ON `tsi`
  FOR EACH ROW
BEGIN 


IF NEW.TTS_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('tsi','tts_codice');
END IF;
IF NEW.TVA_CODICE = ''THEN
  CALL P_CAMPO_VUOTO('tsi','tva_codice');
END IF;
IF NEW.DATA_INIZIO IS NULL THEN
  CALL P_CAMPO_VUOTO('tsi','data_inizio');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
