CREATE TRIGGER T_TTI_BI_0
  BEFORE INSERT
  ON `tti`
  FOR EACH ROW
BEGIN 


IF NEW.TST_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('tti','tst_codice');
END IF;
IF NEW.TVA_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('tti','tva_codice');
END IF;
IF NEW.DATA_INIZIO IS NULL THEN
  CALL P_CAMPO_VUOTO('tti','data_inizio');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
