CREATE TRIGGER T_TVF_BI_0
  BEFORE INSERT
  ON `tvf`
  FOR EACH ROW
BEGIN 


IF NEW.TVA_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('tvf','tva_codice');
END IF;
IF NEW.DATA IS NULL THEN
  CALL P_CAMPO_VUOTO('tvf','data');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
