CREATE TRIGGER T_VDC_BI_0
  BEFORE INSERT
  ON `vdc`
  FOR EACH ROW
BEGIN 


IF NEW.VD2_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('vdc','vd2_codice');
END IF;
IF NEW.SEQUENZA = '' THEN
  CALL P_CAMPO_VUOTO('vdc','sequenza');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
