CREATE TRIGGER T_VDA_BI_0
  BEFORE INSERT
  ON `vda`
  FOR EACH ROW
BEGIN 


IF NEW.ART_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('vda','art_codice');
END IF;
IF NEW.VD1_CODICE = '' THEN
  CALL P_CAMPO_VUOTO('vda','vd1_codice');
END IF;

IF NEW.ID IS NOT NULL THEN
  SET NEW.ID = null;
END IF;

END
